### ISSUE TITLE
Fail to do TreeD task for Direct Deals

### ISSUE THREAD

**Issue by solopine** [filecoin-project/curio#115]
I use Boost and latest main Curio.
When sealing a direct deal, curio failed on TreeD task, the log error is: 
2024-07-22T13:20:33.928+0800	WARN	stores	paths/remote.go:802	reading from remote	{"url": "http://10.0.3.47:12300/remote/piece/s-t00-1", "error": "non-200 code: 416", "errorVerbose": "non-200 code: 416:\n    github.com/filecoin-project/curio/lib/paths.(*Remote).readRemote\n        /root/curio/lib/paths/remote.go:500"}

I check ReaderSeq() function in remote.go (ln 800), there is code:
rd, err := r.readRemote(ctx, url, 0, 0)
The offset and size are both 0, thus the http header "Range" is set to "bytes=0--1", may this leads 416 http error.

**Comment by magik6k** [comment]
Can you describe how you are making the deal?

**Comment by solopine** [comment]
I use the command below:
boostd --boost-repo=/fclotus/.boost import-direct --client-addr=**** --allocation-id=*** baga*** /****.car
The command executed successfully. 
Curio gets the deal and successfully finished the SDR job, but failed at the next job - TreeD.
The cause I analyses is: Getting remote piece fail, http return 416 code. I don't know why calling readRemote by size=0. Now I am trying to do http get with range header, and to see if the TreeD job can work well.

**Comment by LexLuthr** [comment]
This has been fixed the remote.go.
