### ISSUE TITLE
Task release query refers a wrong column

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/curio#2]
https://github.com/filecoin-project/lotus/blob/0c514c534c9ede3163ab51db2cbf62c15374ab26/curiosrc/harmony/harmonytask/harmonytask.go#L184, should be owner_id

One line fix, but want to do the repo extraction first

**Comment by LexLuthr** [comment]
Resolved in Curio main https://github.com/filecoin-project/curio/blob/14a60ce01835c93de21b03c234d429e779294b43/harmony/harmonytask/harmonytask.go#L185

Closing this issue.
