### ISSUE TITLE
Wait until parameters finish loading before starting task scheduler.

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/curio#21]
When starting curio tasks fail because parameters have not finished loading. See the attached files. Sadly the PoRep task fails and does not restart. Parameters take me about 7 minutes to load and these failed tasks could have been scheduled.

> 2024-05-30T05:50:36.965Z	INFO	curio/deps	tasks/tasks.go:218	This Curio instance handles
> 2024-05-30T05:50:37.097Z	INFO	harmonytask	harmonytask/task_type_handler.go:101	did not accept task	{"task_id": 2231, "reason": "CanAccept() refused", "name": "PoRep"}
> 2024-05-30T05:50:37.097Z	ERROR	harmonytask	harmonytask/harmonytask.go:191	Strange: Unable to accept previously owned task	{"id": 2231, "type": "PoRep"}
> 2024-05-30T05:57:00.678Z	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:233	parameter and key-fetching complete

[parameters.txt](https://github.com/filecoin-project/curio/files/15494384/parameters.txt)

**Comment by LexLuthr** [comment]
This has already been fixed in https://github.com/filecoin-project/curio/pull/19
