### ISSUE TITLE
Keep unsealed copy

### ISSUE THREAD

**Issue by MiladZare** [filecoin-project/curio#250]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the Curio forum](https://github.com/filecoin-project/curio/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Curio component

- [ ] PoRep Pipeline
- [ ] Snap Deals
- [ ] Market
- [ ] IPNI provider
- [ ] Curio UI
- [X] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

Currently in Boost if the deal has Keep Unsealed Copy=no and since Curio has no overriding for the behavior, the unsealed copy of the sector won't be kept causing error on Boost side for deal state after sealing state being in proving. There error message is "Paused at 'Waiting for sector to seal': failed to add index and announce deal: failed to add deal to piece metadata store: adding index for piece : getting reader over piece : getting reader over sector 1525: sector is not unsealed."

### Describe the solution you'd like

Add overriding option to Curio like Lotus-miner so miner can keep unsealed copies regardless of the deal properties.
 

From Lotus miner config:
 
  Whether to keep unsealed copies of deal data regardless of whether the client requested that. This lets the miner
  avoid the relatively high cost of unsealing the data later, at the cost of more storage space
  
  type: bool
  env var: LOTUS_SEALING_ALWAYSKEEPUNSEALEDCOPY
  AlwaysKeepUnsealedCopy = true

**Comment by LexLuthr** [comment]
@MiladZare Please note that Curio market is already in progress and it will not be indexing any deals which tell us to not keep the unsealed copy. This will become a non issue in a couple of weeks. Would you still like to pursue this feature? If so, can you please let us know the detailed requirement?

**Comment by MiladZare** [comment]
On that case this wouldn't be needed.
