### ISSUE TITLE
Curio Homepage GUI - PoRep status

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/curio#26]
Once a sector moved to WaitSeed state, the Home page quickly updates the sector status to PoRep even though it is still in WaitSeed. PoRep page is correct however.

Hone Page: (pipeline status incorrect for sector 1)

<img width="824" alt="Home page" src="https://github.com/filecoin-project/curio/assets/49840642/5a04c73c-b35d-4a19-81bc-0fb535e69dd9">

PoRep Page notice Sector 1 status (correct):

<img width="1241" alt="PoRep tab" src="https://github.com/filecoin-project/curio/assets/49840642/3fd8c7be-398c-4d2a-aebc-96343fee2ad2">
 

`git show`

> commit 1c97d3f96397a0662fb701c7ba78e4cc410ae283 (HEAD -> main, origin/main, origin/HEAD)
> Author: LexLuthr <88259624+LexLuthr@users.noreply.github.com>
> Date:   Thu May 30 23:13:18 2024 +0530

**Comment by LexLuthr** [comment]
This problem stems from the fact that there is no waitSeed stage in pipeline anymore. We might have to get smarter and work with seedEpoch value same as PoRep details page. I will write up a PR to fix this in UI.
