### ISSUE TITLE
Boostd does not show publish storage deals for DDO

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/curio#44]
I recently made a deal for DDO and did not see the Publish Storage Deals task run prior to AddPiece:

BoostD logs

> 2024-06-07T19:19:12.724Z	INFO	boost-storage-deal	logs/log.go:40	executing direct deal import	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e", "client": "f3u3353hqrlgxvvw6x3abdkqpqyisgjtgdmmm4aksx2ahjaclmc66lg4jxoaollobb2ngmkpzfdw27bihq6w2a", "piececid": "baga6ea4seaqnyae4fxbz6equc566y6ipnivblomwmsux7px7ey4fhjz64za5kbq"}
> 2024-06-07T19:19:12.740Z	INFO	boost-storage-deal	logs/log.go:40	deal execution initiated	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e", "deal state": "{ID:0ff081cb-51d3-4f04-8815-31968686e28e CreatedAt:2024-06-07 19:19:12.724435606 +0000 UTC PieceCID:baga6ea4seaqnyae4fxbz6equc566y6ipnivblomwmsux7px7ey4fhjz64za5kbq PieceSize:0 Client:f3u3353hqrlgxvvw6x3abdkqpqyisgjtgdmmm4aksx2ahjaclmc66lg4jxoaollobb2ngmkpzfdw27bihq6w2a Provider:f0120800 AllocationID:34717 CleanupData:false InboundFilePath:/home/stuart/small7.car InboundFileSize:0 SectorID:0 Offset:0 Length:0 Checkpoint:Accepted CheckpointAt:0001-01-01 00:00:00 +0000 UTC StartEpoch:1687812 EndEpoch:2206212 Err: Retry:auto KeepUnsealedCopy:true AnnounceToIPNI:true}"}
> 2024-06-07T19:19:12.746Z	INFO	boost-storage-deal	logs/log.go:40	deal execution initiated	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e", "deal state": "{ID:0ff081cb-51d3-4f04-8815-31968686e28e CreatedAt:2024-06-07 19:19:12.724435606 +0000 UTC PieceCID:baga6ea4seaqnyae4fxbz6equc566y6ipnivblomwmsux7px7ey4fhjz64za5kbq PieceSize:0 Client:f3u3353hqrlgxvvw6x3abdkqpqyisgjtgdmmm4aksx2ahjaclmc66lg4jxoaollobb2ngmkpzfdw27bihq6w2a Provider:f0120800 AllocationID:34717 CleanupData:false InboundFilePath:/home/stuart/small7.car InboundFileSize:0 SectorID:0 Offset:0 Length:0 Checkpoint:Accepted CheckpointAt:0001-01-01 00:00:00 +0000 UTC StartEpoch:1687812 EndEpoch:2206212 Err: Retry:auto KeepUnsealedCopy:true AnnounceToIPNI:true}"}
> 2024-06-07T19:19:12.752Z	INFO	boost-storage-deal	logs/log.go:40	size of deal	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e", "filepath": "/home/stuart/small7.car", "size": 1203238}
> 2024-06-07T19:19:12.757Z	INFO	boost-storage-deal	logs/log.go:40	generating commp	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e"}
> 2024-06-07T19:19:12.780 DEBUG filcrypto::util::types > generate_piece_commitment: start
> 2024-06-07T19:19:12.788 DEBUG filcrypto::util::types > generate_piece_commitment: end
> 2024-06-07T19:19:12.789Z	INFO	boost-storage-deal	logs/log.go:40	completed generating commp	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e"}
> 2024-06-07T19:19:12.792Z	INFO	boost-storage-deal	logs/log.go:40	updated deal checkpoint in DB	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e", "old checkpoint": "Accepted", "new checkpoint": "Transferred"}
> 2024-06-07T19:19:12.794Z	INFO	boost-storage-deal	logs/log.go:40	looking up client on chain	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e", "client": "f3u3353hqrlgxvvw6x3abdkqpqyisgjtgdmmm4aksx2ahjaclmc66lg4jxoaollobb2ngmkpzfdw27bihq6w2a"}
> 2024-06-07T19:19:12.796Z	INFO	boost-storage-deal	logs/log.go:40	opening reader over piece data	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e", "filepath": "/home/stuart/small7.car"}
> 2024-06-07T19:19:12.797Z	INFO	boost-storage-deal	logs/log.go:40	adding piece to sector	{"id": "0ff081cb-51d3-4f04-8815-31968686e28e", "filepath": "/home/stuart/small7.car"}

ToolTip on Boost GUI Storage Deals page for Direct Deals -> Deal State

The deal can be in one of the following states:
> Transfer Queued
> The storage deal proposal has been accepted, and Boost is about to start the data transfer.
> 
> Awaiting Offline Data Import
> The client has made an offline deal proposal, and Boost is waiting for the Storage Provider operator to import the deal data.
> 
> Transferring
> The data for the deal is transferring.
> 
> Transfer Complete
> The data transfer is complete and Boost is verifying the data matches commp.
> 
> Ready to Publish
> The deal is in the batch publish queue, ready to be published.
> 
> Awaiting Publish Confirmation
> Boost sent a publish deal message for the deal and is waiting for on-chain confirmation.
> 
> Adding to Sector
> Boost is handing the deal off to the lotus-miner sealing subsystem to be added to a sector.
> 
> Indexing
> Boost is indexing the deal in the Local Index Directory(LID) and will be announcing the deal to the network so that clients know where to retrieve it from.
> 
> IndexedAndAnnounced
> The deal has been indexed locally and announced to the network indexers.
> 
> Complete
> The deal process has finished execution.
> 
> Cancelled
> The deal was cancelled.

**Comment by LexLuthr** [comment]
There is no publishing in DDO. Please don't open Boost related issue in this repo. I would suggest reading on on what DDO is  at https://github.com/filecoin-project/FIPs/discussions/730
