### ISSUE TITLE
Execute curio guided-setup, unable to migrate from existing Lotus-Miner

### ISSUE THREAD

**Issue by Brian44913** [filecoin-project/curio#67]
`Connected to Yugabyte. Schema is current.`
`Enabling Sector Indexing in the database.`
`Error encoding config.toml: parsing updated config: time: missing unit in duration "20000000000"`

**Comment by solopine** [comment]
I also got this error. The root cause of the bug is : Duration type is really int64, when UnmarshalText Duration type data from int64 string by "time.ParseDuration", the error rised.

**Comment by LexLuthr** [comment]
Please build the latest binary. This was fixed after the GA release. 
https://docs.curiostorage.org/installation#linux-build-from-source

When you do `make install`, it will simply replace the binary from apt install. Rest would same from there. 
We would be shipping a new release soon with fixes for `apt`.

**Comment by LexLuthr** [comment]
@Brian44913 @solopine Please let us know if you are migrating your Mainnet miners or Calibnet miners?

**Comment by solopine** [comment]
I used Curio v1.22.0, and build from source, and migrate Mainnet miner. Now I fixed it by adding "MarshalText" method for Duration type in deps/config/types.go.

**Comment by LexLuthr** [comment]
These fixes are already in latest main. We will have a new release with all the fixes at the end of this week.
