### ISSUE TITLE
UI config layer improvements

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/curio#84]
We need to remove 24h tasks column from machine(node) table and add 2 new columns

1. Layers used by node
2. Tasks supported by the node

We should rename "config layer available" to "Source layer" in Actor summary.
<img width="1152" alt="Screenshot 2024-07-10 at 6 22 02 PM" src="https://github.com/filecoin-project/curio/assets/88259624/ddeaf57b-9846-4178-b5dc-64dbda2500e6">

**Comment by magik6k** [comment]
Much agree
