### ISSUE TITLE
Curio logs shows sealing disk errors

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/curio#9]
Sealing disk is NVMe using EXT4, OS is Ubuntu server 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64)

> 2024-05-28T02:00:54.037Z	ERROR	cu/ffi	ffi/sdr_funcs.go:237	reflink treed -> sealed failed, falling back to slow copy, use single scratch btrfs or xfs filesystem	{"error": "reflink is not supported on this OS or file", "sector": {"ID":{"Miner":116748,"Number":1},"ProofType":8}, "cache": "/seal/cache/s-t0116748-1", "sealed": "/seal/sealed/s-t0116748-1"}

> 2024-05-28T01:34:19.376Z	DEBUG	stores	paths/local.go:106	accounting existing files	{"id": {"Miner":116748,"Number":1}, "fileType": "cache", "path": "/seal/cache/s-t0116748-1", "used": 309237682176, "overhead": 484472310988}
> 2024-05-28T01:34:29.452Z	DEBUG	stores	paths/local.go:106	accounting existing files	{"id": {"Miner":116748,"Number":1}, "fileType": "cache", "path": "/seal/cache/s-t0116748-1", "used": 309237682176, "overhead": 484472310988}
> 2024-05-28T01:34:39.456Z	DEBUG	stores	paths/local.go:106	accounting existing files	{"id": {"Miner":116748,"Number":1}, "fileType": "cache", "path": "/seal/cache/s-t0116748-1", "used": 309237682176, "overhead": 484472310988}

PC1 and PC2 succeeding:
`ls -Alh /seal/cache/s-t0116748-1`

> total 421G
> -rw-rw-r-- 1 stuart stuart  32G May 28 01:40 sc-02-data-layer-10.dat
> -rw-rw-r-- 1 stuart stuart  32G May 28 01:59 sc-02-data-layer-11.dat
> -rw-rw-r-- 1 stuart stuart  32G May 27 22:51 sc-02-data-layer-1.dat
> -rw-rw-r-- 1 stuart stuart  32G May 27 23:09 sc-02-data-layer-2.dat
> -rw-rw-r-- 1 stuart stuart  32G May 27 23:28 sc-02-data-layer-3.dat
> -rw-rw-r-- 1 stuart stuart  32G May 27 23:47 sc-02-data-layer-4.dat
> -rw-rw-r-- 1 stuart stuart  32G May 28 00:06 sc-02-data-layer-5.dat
> -rw-rw-r-- 1 stuart stuart  32G May 28 00:24 sc-02-data-layer-6.dat
> -rw-rw-r-- 1 stuart stuart  32G May 28 00:43 sc-02-data-layer-7.dat
> -rw-rw-r-- 1 stuart stuart  32G May 28 01:02 sc-02-data-layer-8.dat
> -rw-rw-r-- 1 stuart stuart  32G May 28 01:21 sc-02-data-layer-9.dat
> -rw-rw-r-- 1 stuart stuart 4.6G May 28 02:07 sc-02-data-tree-c-0.dat
> -rw-rw-r-- 1 stuart stuart  64G May 28 02:00 sc-02-data-tree-d.dat
>

**Comment by LexLuthr** [comment]
Close as this is intended behaviour.
